services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: companydb
    ports:
      - "3309:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chatapp-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8085:8081"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_NAME=companydb
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - chatapp-network

networks:
  chatapp-network:
    driver: bridge