services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: companydb
    ports:
      - "3309:3306"
    volumes:
      - chat-mysql-data:/var/lib/mysql
    networks:
      - app-network

  backend:
    image: backend-image
    build:
      dockerfile: Dockerfile
    ports:
      - "8085:8081" 
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build: .
    ports:
      - "3001:3000" 
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  chat-mysql-data: